version: '3.8'

services:
  backend:
    build: 
      context: ./services/backend
    container_name: collector-backend
    volumes:
      - ./services/backend/data:/app/data
    networks:
      - collector-network

  frontend:
    build:
      context: ./services/frontend
    container_name: collector-frontend
    depends_on:
      - backend
    networks:
      - collector-network

networks:
  collector-network:
    driver: bridge